export const READ_PRODUCT = 'READ_PRODUCT';
export const READ_PRODUCT_SUCCESS = 'READ_PRODUCT_SUCCESS';
export const PRODUCT_NUMBER = 'PRODUCT_NUMBER';
export const ADD_PRODUCTS_FROM_VIEW_PAGE = 'ADD_PRODUCTS_FROM_VIEW_PAGE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUsCT';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

